source 'https://github.com/CocoaPods/Specs.git'

target 'SACollectionViewVerticalScalingFlowLayout', :exclusive => true do
  pod "SACollectionViewVerticalScalingFlowLayout", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SACollectionViewVerticalScalingFlowLayout", :path => "../"

  
end
